djangoProjectIostream/urls.py
from django.contrib import admin
from django.urls import path, include
from djangoMainPage import views as main_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.HomeView.as_view(), name='main'),
    path('lecture/', include("djangoLecturePage.urls")),
    path('news/', include("djangoNewsPage.urls")),
    path('logout/', main_views.LogoutView.as_view(), name='logout'),
    path('accounts/', include('djangoUsers.urls')),
]

djangoUsers/urls.py
from django.urls import path, include
from djangoUsers.views import Register

urlpatterns = [
    path('register/', Register.as_view(), name='register'),
]

djangoUsers/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models


class CustomUser(AbstractUser):
    STATUS = (
        ('Student', 'Студент'),
        ('School', 'Мектеп оқушысы'),
        ('Teacher', 'Мұғалім'),
        ('Other', 'Басқа')
    )

    city = models.CharField(max_length=50, null=True, blank=True, default='')
    status = models.CharField(max_length=10, choices=STATUS, default='Student')
    birth_date = models.DateField(null=True, blank=True, default='2001-09-11')
    phone = models.CharField(
        max_length=15,
        null=True,
        blank=True,
        default='',
        validators=[RegexValidator('\+[0-9]{1}\([0-9]{3}\)[0-9]{3}\-[0-9]{4}')],
        error_messages='Телефон нөмірі қате енгізілді.'
    )
    subscribe = models.BooleanField(default=False)

djangoUsers/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from djangoUsers.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = CustomUser
        # fields = '__all__'
        fields = ('username', 'first_name', 'last_name', 'email', 'phone', 'status', 'birth_date', 'city', 'password1', 'password2', )

    def clean_email(self):
        email = self.cleaned_data['email']
        if CustomUser.objects.filter(email=email).exists():
            raise ValidationError("Электрондық пошта бұрыннан бар")

        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if CustomUser.objects.filter(username=username).exists():
            raise ValidationError("Пайдаланушы аты бұрыннан бар")

        return username

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if CustomUser.objects.filter(phone=phone).exists():
            raise ValidationError("Телефон номер бұрыннан бар")

        return phone


    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

djangoUsers/views.py
from django.contrib.auth import authenticate, login
from djangoUsers.forms import CustomUserCreationForm
from django.views.generic import View
from django.shortcuts import render, redirect


class Register(View):

    template_name = 'users/register.html'

    def get(self, request):
        context = {
            'form': CustomUserCreationForm(),
        }
        return render(request, template_name=self.template_name, context=context)

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password, email=email)
            login(request, user)
            return redirect('main')
        context = {
            'form': form,
            'error': form.errors,
        }
        return render(request, self.template_name, context)

djangoUsers/templates/users/register.html
{% extends 'main/index.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "users/register.css" %}">
    <script src="https://code.jquery.com/jquery-2.2.4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
{% endblock %}

{% block content %}
            <div class="form signup container">
                <div class="form-content">
                    <form action="#" method="POST">
                        {% csrf_token %}
                        <div class="field input-field">
                            <input type="email" name="email" placeholder="Электрондық пошта" class="input" required>
                        </div>
                        
{#                        <div class="field input-field">#}
{#                            <input type="tel" id="phone" name="phone" placeholder="Телефон номер" class="input" pattern="[0-9]{11}" required>#}
{#                        </div>#}
                        
                        <div class="field input-field">
                            <input type="text" name="username" placeholder="Пайдаланушы аты" class="input" required>
                        </div>
                    
                        <div class="field input-field">
                            <input type="text" name="first_name" placeholder="Аты" class="input" required>
                        </div>
                    
                        <div class="field input-field">
                            <input type="text" name="last_name" placeholder="Тегі" class="input" required>
                        </div>
                        
                        <div class="field input-field">
                            <input type="tel" name="phone" placeholder="Телефон номер" class="phone" required>
                        </div>
                    
                        <div class="field input-field">
                            <input type="text" name="city" placeholder="Қала" class="input" required>
                        </div>
                    
                        <div class="field input-field">
                            <input type="date" name="birth_date" placeholder="Туылған күн" class="date" required>
                        </div>
                    
                        <div class="field input-field">
                            <select name="status" class="form-select" id="id_status">
                              <option value="Student" selected="">Студент</option>
                            
                              <option value="School">Мектеп оқушысы</option>
                            
                              <option value="Teacher">Мұғалім</option>

                              <option value="Other">Басқа</option>
                            
                            </select>
                        </div>

                        <div class="field input-field">
                            <input type="password" name="password1" placeholder="Құпия сөз жасаңыз" class="password" required>
                        </div>

                        <div class="field input-field">
                            <input type="password" name="password2" placeholder="Құпия сөзді Растау" class="password" required>
                            <i class='bx bx-hide eye-icon'></i>
                        </div>
                        
                        {% if error %}
                        <div class="error">
                            {{ error }}
                        </div>
                        {% endif %}

                        <div class="field button-field">
                            <button type="submit">Тіркелу</button>
                        </div>
                    </form>

{#                    <div class="form-link">#}
{#                        <span>Already have an account? <a href="#" class="link login-link">Login</a></span>#}
{#                    </div>#}
                </div>

{#                <div class="line"></div>#}
{##}
{#                <div class="media-options">#}
{#                    <a href="#" class="field facebook">#}
{#                        <i class='bx bxl-facebook facebook-icon'></i>#}
{#                        <span>Login with Facebook</span>#}
{#                    </a>#}
{#                </div>#}
{##}
{#                <div class="media-options">#}
{#                    <a href="#" class="field google">#}
{#                        <img src="#" alt="" class="google-img">#}
{#                        <span>Login with Google</span>#}
{#                    </a>#}
{#                </div>#}
            </div>
    <script src="{% static 'users/register.js' %}"></script>
{% endblock %}